This is makeindex, version 2.15 [MiKTeX 2.9.6500 64-bit] (kpathsea + Thai support).
Scanning style file ./Yuwen_thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Yuwen_thesis.acn....done (39 entries accepted, 0 rejected).
Sorting entries....done (205 comparisons).
Generating output file Yuwen_thesis.acr....done (44 lines written, 0 warnings).
Output written in Yuwen_thesis.acr.
Transcript written in Yuwen_thesis.alg.
